class ChampionWrapper():
    def __init__(self):
       self.idToChamp = {
            0: 'Other',
            1: 'Annie',
            2: 'Olaf',
            3: 'Galio',
            4: 'Twisted Fate',
            5: 'Xin Zhao',
            6: 'Urgot',
            7: 'LeBlanc',
            8: 'Vladimir',
            9: 'Fiddlesticks',
            10: 'Kayle',
            11: 'Master Yi',
            12: 'Alistar',
            13: 'Ryze',
            14: 'Sion',
            15: 'Sivir',
            16: 'Soraka',
            17: 'Teemo',
            18: 'Tristana',
            19: 'Warwick',
            20: 'Nunu',
            21: 'Miss Fortune',
            22: 'Ashe',
            23: 'Tryndamere',
            24: 'Jax',
            25: 'Morgana',
            26: 'Zilean',
            27: 'Singed',
            28: 'Evelynn',
            29: 'Twitch',
            30: 'Karthus',
            31: "Cho'Gath",
            32: 'Amumu',
            33: 'Rammus',
            34: 'Anivia',
            35: 'Shaco',
            36: 'Dr. Mundo',
            37: 'Sona',
            38: 'Kassadin',
            39: 'Irelia',
            40: 'Janna',
            41: 'Gangplank',
            42: 'Corki',
            43: 'Karma',
            44: 'Taric',
            45: 'Veigar',
            46: 'Trundle',
            47: 'Swain',
            48: 'Caitlyn',
            49: 'Blitzcrank',
            50: 'Malphite',
            51: 'Katarina',
            52: 'Nocturne',
            53: 'Maokai',
            54: 'Renekton',
            55: 'Jarvan IV',
            56: 'Elise',
            57: 'Orianna',
            58: 'Wukong',
            59: 'Brand',
            60: 'Lee Sin',
            61: 'Vayne',
            62: 'Rumble',
            63: 'Cassiopeia',
            64: 'Skarner',
            65: 'Heimerdinger',
            66: 'Nasus',
            67: 'Nidalee',
            68: 'Udyr',
            69: 'Poppy',
            70: 'Gragas',
            71: 'Pantheon',
            72: 'Ezreal',
            73: 'Mordekaiser',
            74: 'Yorick',
            75: 'Akali',
            76: 'Kennen',
            77: 'Garen',
            78: 'Leona',
            79: 'Malzahar',
            80: 'Talon',
            81: 'Riven',
            82: "Kog'Maw",
            83: 'Shen',
            84: 'Lux',
            85: 'Xerath',
            86: 'Shyvana',
            87: 'Ahri',
            88: 'Graves',
            89: 'Fizz',
            90: 'Volibear',
            91: 'Rengar',
            92: 'Varus',
            93: 'Nautilus',
            94: 'Viktor',
            95: 'Sejuani',
            96: 'Fiora',
            97: 'Ziggs',
            98: 'Lulu',
            99: 'Draven',
            100: 'Hecarim',
            101: "Kha'Zix",
            102: 'Darius',
            103: 'Jayce',
            104: 'Lissandra',
            105: 'Diana',
            106: 'Quinn',
            107: 'Syndra',
            108: 'Aurelion Sol',
            109: 'Kayn',
            110: 'Zoe',
            111: 'Zyra',
            112: "Kai'Sa",
            113: "Seraphine",
            114: 'Gnar',
            115: 'Zac',
            116: 'Yasuo',
            117: "Vel'Koz",
            118: 'Taliyah',
            119: "Akshan",
            120: 'Camille',
            121: 'Braum',
            122: 'Jhin',
            123: 'Kindred',
            124: 'Jinx',
            125: 'Tahm Kench',
            126: 'Viego',
            127: 'Senna',
            128: 'Lucian',
            129: 'Zed',
            130: 'Kled',
            131: 'Ekko',
            132: 'Qiyana',
            133: 'Vi',
            134: 'Aatrox',
            135: 'Nami',
            136: 'Azir',
            137: 'Yuumi',
            138: 'Samira',
            139: 'Thresh',
            140: 'Illaoi',
            141: "Rek'Sai",
            142: 'Ivern',
            143: 'Kalista',
            144: 'Bard',
            145: 'Rakan',
            146: 'Xayah',
            147: 'Ornn',
            148: 'Sylas',
            149: 'Rell',
            150: 'Neeko',
            151: 'Aphelios',
            152: 'Pyke',
            153: "Sett",
            154: "Vex",
            155: "Yone",
            156: "Gwen",
            157: "Lillia",
       }

       self.champToID = {b:a for a, b in self.idToChamp.items()}


    def cIdToName(self, _id):
        """
        this functions takes an _id and returns the associate champions name
        :param _id: any integer from 1 to 555. if there is a champion, it will return the name.
        :return: champions name
        """
        return self.idToChamp.get(id, 'Other')

    def cNameToId(self, name):
        return self.champToID.get(name, 0)